### ISSUE TITLE
Unable to kubeadm init without dry-run flag

### ISSUE THREAD

**Issue by aferrar** [SpaceAceMonkey/spaceace-arch-kubernetes-unraid#2] opened 2022-07-16 18:01 UTC
Hi! Thanks for this awesome guide. I am having issues with the dry-run vs actual for initializing Kubernetes on my master VM. It seems to work fine in the dry-run:

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/11024203/179366820-7e3437b8-b251-4a8b-84d2-e90cf03e1b2b.png">

But the command hangs on the following when I remove the dry-run flag:

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/11024203/179366843-ca6aadeb-04b0-46b6-9422-1fd79c1fb132.png">

Any help is greatly appreciated!

**Comment by SpaceAceMonkey** [comment] 2022-07-18 02:48
From the screenshots, this looks like a networking issue. The `dial tcp: lookup dl.k8s.io: no such host` means kubeadm can't find the address for `dl.k8s.io`. Kubadm is trying to fetch information about the latest stable release of Kubernetes, but it can't reach the internet.

What happens if you try `ping google.com` from that virtual machine? Does it successfully find google.com's IP address? What about pinging `dl.k8s.io`? Can you use `curl`, or `wget`, or something similar to fetch pages from other hosts on the internet?

Your initial title for this issue mentions changing the network configuration, and that's probably a good place to start looking.

**Comment by aferrar** [comment] 2022-07-21 15:50
I get "Destination host unreachable" when I attempt to ping google. I think I broke something when attempting to set the static ip. Please see below for my network config. The DNS servers are piholes on my network with dhcp disabled. My router is serving dhcp and using the piholes for dns. Are there any other config files I can check to try and narrow down the cause of my issue? Any help is greatly appreciated!

<img width="266" alt="image" src="https://user-images.githubusercontent.com/11024203/180257716-7ca2c113-5896-420d-aba5-797ad6eb6146.png">

**Comment by SpaceAceMonkey** [comment] 2022-07-31 07:07
I have the same network setup you describe, except that I have only one PiHole, so that can probably be eliminated as the cause of the problem.

Is your static IP successfully assigned to your networking interface? What does `ip route show` give you? Does networking work if you allow the IP to be assigned via DHCP? Can you ping the gateway?

**Closed as completed** 2024-08-04 04:01 UTC
